config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'posts#index'

  get "pricing", to: "static_pages#pricing"

  resources :posts do
    member do 
      patch  "upvote"
      patch  "downvote"
      #, to: "posts#upvote"
    end
  end
  
  post "checkout/create", to: "checkout#create", as: "checkout_create"

  post "billing_portal/create", to: "billing_portal#create", as: "billing_portal_create"

  resources :webhooks, only: [:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord

    validates :title, :content, presence: true

    acts_as_votable 

    scope :free, -> { where(premium: false) }

    def to_s
        title 
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_voter 
         
  def to_s
    email
  end

  after_create do
    customer = Stripe::Customer.create(email: self.email)
    #this logic moved to webhooks
    update(stripe_customer_id: customer.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/billing_portal_controller.rb
class BillingPortalController < ApplicationController
    def create
        @portal_session = Stripe::BillingPortal::Session.create({
            customer: current_user.stripe_customer_id,
            return_url: root_url
        })
        
        redirect_to @portal_session.url, allow_other_host: true

        rescue Stripe::InvalidRequestError => error
        # redirect back to your shopping cart or previous URL here if there's an error
            redirect_to root_url, alert: error.message 
    end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    @session = Stripe::Checkout::Session.create({
                                       customer: current_user.stripe_customer_id,
                                       success_url: posts_url,
                                       cancel_url: pricing_url,
                                       line_items: [
                                         { price: params[:price], quantity: 1 }
                                       ],
                                       payment_method_types: [
                                         'card'
                                       ],
                                       mode: 'subscription'
                                     })  

    redirect_to @session.url, allow_other_host: true

    rescue Stripe::InvalidRequestError => error
    # redirect back to your shopping cart or previous URL here if there's an error
    redirect_to pricing_url, alert: error.message 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy upvote downvote]

  def downvote 
    if current_user.voted_down_on? @post
        @post.unvote_by current_user
    else
      @post.downvote_by current_user     
    end
    respond_to do |format|
      format.html do
        redirect_to @post 
      end
      format.turbo_stream do 
        render turbo_stream: turbo_stream.replace(@post, partial: 'posts/post', locals: { post: @post } )
      end
    end  
  end


  def upvote 
    if current_user.voted_up_on? @post
        @post.unvote_by current_user
    else
      @post.upvote_by current_user     
    end
    respond_to do |format|
      # format.html do
      #   redirect_to @post 
      # end
      format.turbo_stream do 
        render turbo_stream: turbo_stream.replace(@post, partial: 'posts/post', locals: { post: @post } )
      end
    end 
        # @post = Post.find(params[:id])
        # if current_user.voted_up_on? @post 
        #   @post.unvote_by current_user
        # else
        #   @post.upvote_by current_user 
        # end  
        # respond_to do |format|
        #   format.js { render 'vote' }
        # end  
  end

  # GET /posts or /posts.json
  def index
    if current_user.subscription_status == "active"
      @posts = Post.all.order(id: :desc)
    else
      @posts = Post.free.order(id: :desc)
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
    if @post.premium? && current_user.subscription_status != "active"
       redirect_to posts_path, alert: "Only for active subscribers"
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :premium)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController 
    def pricing 
    end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
    skip_before_action :authenticate_user!
    skip_before_action :verify_authenticity_token

    def create
        payload = request.body.read 
        sig_header = request.env['HTTP_STRIPE_SIGNATURE']
        endpoint_secret = Rails.application.credentials.dig(:stripe, :webhook)
        event = nil 

        begin
            event = Stripe::Webhook.construct_event(
                payload, sig_header, endpoint_secret
            )
        rescue JSON::ParserError => e
            render plain: "Invalid JSON.", status: 400
            return
        rescue Stripe::SignatureVerificationError => e
           puts "Signature error controller"
           p e 
           return
        end
        
        case event.type
        when 'customer.created'
            customer = event.data.object 
            @user = User.find_by(email: customer.email)
            @user.update(stripe_customer_id: customer.id)
        when 'checkout.session.completed'
            session = event.data.object
            @user = User.find_by(stripe_customer_id: session.customer)
            @user.update(subscription_status: 'active')
        when 'customer.subscription.updated', 'customer.subscription.deleted'
            subscription = event.data.object
            @user = User.find_by(stripe_customer_id: subscription.customer)
            @user.update(
                subscription_status: subscription.status,
                plan: subscription.items.data[0].price.lookup_key
            )
        end 
        render json: { message: 'success' }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/checkout/create.js.erb
var stripe = Stripe("<%= Rails.application.credentials[:stripe][:public] %>");
stripe.redirectToCheckout({
    sessionId: '<%= @session.id %>'
}).then(function(result) {
    console.log(result.error.message);
})

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saasblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">

    <script src="https://js.stripe.com/v3/"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= Time.zone.now %>
    <br>
  <div style="display:inline-block;">
      <%= button_to "Posts", posts_path, form: {style: 'display:inline-block;'} %>
      <%= button_to "Pricing", pricing_path, form: {style: 'display:inline-block;'}  %>
      <% if current_user %>
        <%= button_to "Billing portal", billing_portal_create_path, method: :post, data: { turbo: false }, form: {style: 'display:inline-block;'}  %>
        <%= button_to current_user.email, edit_user_registration_path, method: :get, form: {style: 'display:inline-block;'}  %>
        <%= button_to "Log out", destroy_user_session_path, method: :get, data: { turbo: false }, form: {style: 'display:inline-block;'}  %>
        <br>
          Stripe customer id:
          <%= current_user.stripe_customer_id%>
          <br>
          Plan:
          <%= current_user.plan%>
          <br>
          Subscription status:
          <%= current_user.subscription_status%>
      <% else %>
        <%= button_to "Log in", new_user_session_path %>
        <%= button_to "Register", new_user_registration_path %>
      <% end %>
  </div>    
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :premium, style: "display: block" %>
    <%= form.check_box :premium %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

  <p>
    <strong>Premium:</strong>
    <%= post.premium %>
  </p>

  <p>
        Score:
        <%= post.cached_weighted_score %>
  <p>
  <p>
        Upvotes:
        <%= post.cached_votes_up %>
  <p>
  <p>
        Downvotes:
        <%= post.cached_votes_down %>
  <p>  

        <%= button_to "Upvote", upvote_post_path(post), method: :patch %>    
        <%= button_to "Downvote", downvote_post_path(post), method: :patch %>         

</div>

app/views/posts/_upvote_link.html.erb
<%= content_tag "div", id:"upvote-#{post.id}" do %>
    <%= button_to upvote_post_path(post), method: :patch, remote: true do %>
        <% if current_user.voted_up_on? post %>
            unvote
        <% else %>
            vote!
        <%end%>
    <%end%>
<%end%>

app/views/posts/_votes_score.html.erb
<%= content_tag "div", id:"votes_score-#{post.id}" do %>
    <%= post.cached_votes_score %>
<% end %>    

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<%= button_to "New post", new_post_path, method: :get, data: { turbo: false }, form: {style: 'display:inline-block;'}  %>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%# AJAX  %>
      <%# <%= render "posts/votes_score", post: post%>     %>
      <%# <%= render "posts/upvote_link", post: post%> %>
      <%= button_to "Show", post %>
    </p>
  <% end %>
</div>

<%= button_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/posts/vote.js.erb
document.getElementById("upvote-<%= @post.id %>").innerHTML = "<%= j render "posts/upvote_link", post: @post %>";
document.getElementById("votes-score-<%= @post.id %>").innerHTML = "<%= j render "posts/votes_score", post: @post %>";

app/views/static_pages/pricing.html.erb
<h1>Pricing</h1>


<% @pricing = Stripe::Price.list(expand: ["data.product"])%>
<% @pricing.each do |price| %>
    <br>
    <%= price.product.name%>
    <%= price.id %>
    <%= price.unit_amount/100 %>
    <%= price.currency %>
    <%= price.recurring.interval %>
    <%= button_to "Checkout", checkout_create_path(price: price.id), method: :post, data: { turbo: false } %>
<%end%>